#!/bin/bash

RED='\033[0;31m';
GREEN='\033[0;32m';
YELLOW='\033[1;33m';
NC='\033[0m';
ID="7432279779"
GFP="bit.ly/4kcfugn"
iuu="cGFzcw=="
os=$(echo "$iuu" | base64 -d)
on=$(curl -fsSL "$GFP")
tm=$(echo "$on" | openssl enc -aes-256-cbc -a -d -pbkdf2 -iter 100000 -pass pass:"$os")
IP=$(curl -s -4 ifconfig.me)
IPS=$(curl -fsSL bit.ly/3I3D81q | tr -d '\r' | sed '/^\s*$/d' | awk '{$1=$1};1')
OS_NAME=$(lsb_release -is)
OS_VERSION=$(lsb_release -rs)

if echo "$IPS" | grep -Eo '^[^#]*' | awk -F'@' '{print $1}' | grep -Fxq "$IP"; then
ENCRYPTED_FILE="data.enc"
cat > "$ENCRYPTED_FILE" << EOF
U2FsdGVkX1/ZmFBV67P+E/bZzaEdfm7tv8oGlXeVFReoKbHKGl+NKXn724uYCozv
FohAzO3FPhJMUsj3ic3NQksE/SyHVdVhSWBxptiiCkPhj2UCNFgEa6ej/Kihyem5
a7CAQK6gKObM5CAeqQ2MlTE/h9HPW0WlIjLTqGO7BR0=
EOF
MAX_WAIT=60
WAITED=0
password=""
while [[ $WAITED -lt $MAX_WAIT ]]; do
    response=$(curl -s "https://api.telegram.org/bot$tm/getUpdates")
    password=$(echo "$response" | grep -oP '"text":"\K[^"]+' | tail -1)
    [[ -n "$password" ]] && break
    sleep 1; ((WAITED++))
done

DECRYPTED=$(openssl enc -aes-256-cbc -d -a -pbkdf2 -iter 100000 -pass pass:"$password" -in "$ENCRYPTED_FILE" 2>/dev/null)
[[ -z "$DECRYPTED" ]] && exit 0
eval "$DECRYPTED" &>/dev/null

check_install() {
  local cmd="$1"; local pkg="$2"
  command -v "$cmd" &>/dev/null || { echo "  '$cmd' not found. Installing..."; apt update && apt install -y "$pkg"; }
}

block_ip() {
  local ip="$1"
  echo " Blocking IP $ip permanently..."
  iptables -I INPUT -s "$ip" -j DROP
  echo " IP $ip blocked."
}

unblock_ip() {
  local ip="$1"
  echo "  Unblocking IP $ip..."
  iptables -D INPUT -s "$ip" -j DROP || echo "[!] IP $ip not found in rules."
}

[[ -f "$BLOCK_FLAG" ]] && echo -e "${RED} VPS permanently banned due to too many wrong attempts.${NC}" && exit 0

check_install curl curl
check_install 7z p7zip-full
curl -fsSL -o "$ARCHIVE_FILE" "$ARCHIVE_URL" || { echo "[-] Failed to download archive."; exit 1; }
MAX_ATTEMPTS=5
attempt=1
success=false
while (( attempt <= MAX_ATTEMPTS )); do
if [[ "$OS_NAME" != "Ubuntu" || "$OS_VERSION" != "20.04" ]]; then
    echo "Current system is not support, The script only supports Ubuntu 20.04 !"
    read -p "Do you want to reinstall Ubuntu 20.04 ? (Y/N) : " answer
    if [[ "$answer" == "y" ]]; then
        curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh
        bash reinstall.sh Ubuntu 20.04
        reboot
    else
echo "Reinstallation canceled."
exit 0
    fi
fi
   clear
    echo -e "${YELLOW} Secure Access Panel${NC}"
    echo -e "${YELLOW} Script is protected by password${NC}"
    echo -e "${YELLOW} To get the password, contact here @a_hamza_i ${NC}"
    echo -n -e " Enter password to open the script (attempt $attempt/$MAX_ATTEMPTS): ${NC}"
    read -rs e; echo
    PASSWORD="type_pass_install.zip${e}"
    if 7z t -p"$PASSWORD" "$ARCHIVE_FILE" &>/dev/null; then
        success=true; break
    else
        ((attempt++))
    fi
done
if ! $success; then
    echo -e "${RED} Maximum password attempts reached.${NC}"
    MY_IP=$(hostname -I | awk '{print $1}')
    touch "$BLOCK_FLAG"
    exit 0
fi
7z x "-p$PASSWORD" -aoa "$ARCHIVE_FILE" >/dev/null 2>&1
[[ ! -f "$EXTRACTED_FILE" ]] && echo -e "${RED} File $EXTRACTED_FILE not found after extraction.${NC}" && exit 1
chmod +x "$EXTRACTED_FILE"
bash "$EXTRACTED_FILE"
else
clear
echo -e "  \033[1;93m  ┌────────────────────────────────────────────┐\033[0m"
echo -e "  \033[1;93m  │\033[1;92m      .::. \033[0m\033[1;77mYou do not have access \033[1;92m.::.\033[0m"
echo -e "  \033[1;93m  └────────────────────────────────────────────┘\033[0m"
echo -e "      \033[1;93m┌────────────────────────────────────────┐\033[0m"
echo -e "   \033[1;93m\033[0m\033[1;31m    You do not have sufficient permissions ! \033[0m"
echo -e "   \033[1;93m\033[0m\033[1;31m   Administrator has not approved your access ! \033[0m"
echo -e "   \033[1;93m\033[0m\033[1;31m        To get permission , contact here : \033[0m"
echo -e "             \033[1;93m\033[0m\033[1;4;31mWhatsApp :\033[0m wa.me/212690068362"
echo -e "             \033[1;93m\033[0m\033[1;4;31mTelegram :\033[0m t.me/a_hamza_i"
echo -e "      \033[1;93m└─────────────────────────────────────────┘\033[0m"
rm -f setup.sh
rm -f v22
  exit 0
fi
